#!/bin/sh
CC="/home/lab4/yasugi/tmp/i386-linux2.4.20/n1/bin/gcc -O2 -lm -pthread systhr-i386.o"

if [ $# -ge 1 ] && [ `which $1` ]
then
LANG=C $CC -v
LANG=C $CC nqueen-c.c -o nqueen-c
LANG=C $CC nqueen-gcc.c -o nqueen-gcc
LANG=C $CC nqueen.c nestfunc.c -o nqueen-lw
LANG=C $CC nqueen-xcc.c -o nqueen-xcc # XC-cube lightweight
LANG=C $CC nqueen-clos.c nestfunc.c -o nqueen-clos
fi

if [ $# -le 1 ]; then
 m=1
else
 m=$2
fi

if [ $# -le 2 ]; then
 n=13
else
 n=$3
fi

progs="./nqueen-c ./nqueen-gcc ./nqueen-lw ./nqueen-xcc ./nqueen-clos"

if [ $# -le 2 ]; then
 n=13
else
 n=$3
fi

for prog in $progs; do
    i=0
    echo $prog
    while [ $i -lt $m ]; do
	$prog $arg1 $n && sleep 0.3
	i=`expr $i + 1`
    done
    arg1=1
    echo ""
done
