#!/bin/sh
if [ $# -ge 1 ] && [ `which $1` ]
then
LANG=C $1 -v
LANG=C $1 -O2 nqueen-c.c -o nqueen-c
LANG=C $1 -O2 -DNOXCC nqueen-gcc.c -o nqueen-gcc
LANG=C $1 -O2 -DNOXCC nqueen.c nestfunc.c -o nqueen-lw
LANG=C $1 -O2 -DNOXCC nqueen-clos.c nestfunc.c -o nqueen-clos
fi

if [ $# -le 1 ]; then
 m=1
else
 m=$2
fi

if [ $# -le 2 ]; then
 n=13
else
 n=$3
fi

progs="./nqueen-c ./nqueen-gcc ./nqueen-lw ./nqueen-clos"

if [ $# -le 2 ]; then
 n=13
else
 n=$3
fi

for prog in $progs; do
    i=0
    echo $prog
    while [ $i -lt $m ]; do
	$prog $arg1 $n && sleep 0.3
	i=`expr $i + 1`
    done
    arg1=1
    echo ""
done
