#! /bin/sh
if [ $# -ge 1 ] && [ `which $1` ]
then
gcc -v
$1 -O2 cpfib0.c -DRAWC -o cpfib-c
$1 -O2 cpfib0.c -o cpfib-gcc
$1 -O2 cpfib.c nestfunc.c -o cpfib-lw
LANG=C /home/lab4/yasugi/tmp/i386-linux2.4.20/n1/bin/gcc -DCT=lightweight -O2 cpfib0.c copygc0.c -o cpfib-xcc # XC-cube lightweight
$1 -O2 cpfib-clos.c -o cpfib-clos
fi

if [ $# -le 1 ]; then
 m=1
else
 m=$2
fi

progs="./cpfib-c ./cpfib-gcc ./cpfib-lw ./cpfib-xcc ./cpfib-clos"

if [ $# -le 2 ]; then
 n=34
else
 n=$3
fi

for prog in $progs; do
    i=0
    echo $prog
    while [ $i -lt $m ]; do
	$prog $n && sleep 0.3
	i=`expr $i + 1`
    done
    arg1=1
    echo ""
done

