/* src/config.h.  Generated by configure.  */
/* src/config.h.in.  Generated from configure.ac by autoheader.  */

/* Define if '0x5c' in BIGFIVE multi-byte character is safe. */
/* #undef BIGFIVE_IS_ESCAPE_FREE */

/* Define if adjacent string literals are concatenated. */
#define CAN_CONCAT_STRINGS 1

/* Define the compiler. */
#define COMPILER GNUC

/* Define the type of size_t. */
#define COMPILER_SP1_VAL "unsigned int"

/* Define the type of ptrdiff_t. */
#define COMPILER_SP2_VAL "int"

/* Define the type of wchar_t. */
#define COMPILER_SP3_VAL "short unsigned int"

/* Define the name of COMPILER-specific OLD-style predefined macro. */
/* #undef COMPILER_SP_OLD */

/* Define the value of COMPILER-specific OLD-style predefined macro. */
/* #undef COMPILER_SP_OLD_VAL */

/* Define the name of COMPILER-specific STD-style predefined macro. */
/* #undef COMPILER_SP_STD */

/* Define the value of COMPILER-specific STD-style predefined macro. */
/* #undef COMPILER_SP_STD_VAL */

/* Define the C++ include directory. */
/* #undef CPLUS_INCLUDE_DIR1 */

/* Define compiler-specific C++ include directory 2. */
/* #undef CPLUS_INCLUDE_DIR2 */

/* Define the cpu-specific-predefined-macro. */
#define CPU_OLD "i386"

/* Define the name of CPU-specific OLD-style predefined macro. */
/* #undef CPU_SP_OLD */

/* Define the value of CPU-specific OLD-style predefined macro. */
/* #undef CPU_SP_OLD_VAL */

/* Define the name of CPU-specific STD-style predefined macro. */
/* #undef CPU_SP_STD */

/* Define the value of CPU-specific STD-style predefined macro. */
/* #undef CPU_SP_STD_VAL */

/* Define the cpu-specific-predefined-macro. */
#define CPU_STD1 "__i386"

/* Define the cpu-specific-predefined-macro. */
#define CPU_STD2 "__i386__"

/* Define compiler-specific include directory 1. */
/* #undef C_INCLUDE_DIR1 */

/* Define if the argument of pragma is macro expanded. */
/* #undef EXPAND_PRAGMA */

/* Define if the cases of file name are folded. */
#define FNAME_FOLD 1

/* Define gcc major version. */
#define GCC_MAJOR_VERSION "3"

/* Define gcc minor version. */
#define GCC_MINOR_VERSION "4"

/* Define if backslash-a works in C strings. */
#define HAVE_C_BACKSLASH_A 1

/* Define if digraphs are available. */
#define HAVE_DIGRAPHS 1

/* Define to 1 if you have the `getenv' function. */
#define HAVE_GETENV 1

/* Define to 1 if you have the `getopt' function. */
#define HAVE_GETOPT 1

/* Define to 1 if the system has the type `intmax_t'. */
#define HAVE_INTMAX_T 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <limits.h> header file. */
#define HAVE_LIMITS_H 1

/* Define to 1 if the system has the type `long double'. */
#define HAVE_LONG_DOUBLE 1

/* Define to 1 if the system has the type `long long'. */
#define HAVE_LONG_LONG 1

/* Define to 1 if you have the `memcmp' function. */
#define HAVE_MEMCMP 1

/* Define to 1 if you have the `memcpy' function. */
#define HAVE_MEMCPY 1

/* Define to 1 if you have the `memmove' function. */
#define HAVE_MEMMOVE 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define if pragma directive can be used. */
#define HAVE_PRAGMA 1

/* Define if fgets retains the last line after EOF. */
#define HAVE_SANE_FGETS 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the `stpcpy' function. */
/* #undef HAVE_STPCPY */

/* Define to 1 if you have the `strcspn' function. */
#define HAVE_STRCSPN 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the `strstr' function. */
#define HAVE_STRSTR 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <time.h> header file. */
#define HAVE_TIME_H 1

/* Define to 1 if the system has the type `time_t'. */
#define HAVE_TIME_T 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 if the system has the type `unsigned long'. */
#define HAVE_UNSIGNED_LONG 1

/* Define to 1 if the system has the type `__int64'. */
/* #undef HAVE___INT64 */

/* Define the host system. */
#define HOST_SYSTEM SYS_SYGWIN

/* Define if '0x5c' in ISO2022_JP multi-byte character is safe. */
/* #undef ISO2022_JP_IS_ESCAPE_FREE */

/* Define if the library is glibc. */
/* #undef LIB_IS_GLIBC */

/* Define output format of line directive. */
#define LINE_PREFIX "# "

/* Define printf length modifier for the longest integer. */
#define LL_FORM "j"

/* Define the suffix of object file. */
#define OBJEXT "o"

/* Name of package */
#define PACKAGE "mcpp"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "kmatsui@t3.rim.or.jp"

/* Define to the full name of this package. */
#define PACKAGE_NAME "mcpp"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "mcpp 2.4.1"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "mcpp"

/* Define to the version of this package. */
#define PACKAGE_VERSION "2.4.1"

/* Define to 1 if the C compiler supports function prototypes. */
#define PROTOTYPES 1

/* Define include preference. */
#define SEARCH_INIT SOURCE

/* Define if '0x5c' in SJIS multi-byte character is safe. */
/* #undef SJIS_IS_ESCAPE_FREE */

/* Define the default value of __STDC__. */
#define STDC 1

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Define the default value of __STDC_VERSION__. */
#define STDC_VERSION 0

/* Define whether output format of line directive is C source style. */
#define STD_LINE_PREFIX 0

/* Define the target system. */
#define SYSTEM SYS_CYGWIN

/* Define the version of FreeBSD. */
/* #undef SYSTEM_EXT_VAL */

/* Define the name of SYSTEM-specific OLD-style predefined macro. */
/* #undef SYSTEM_SP_OLD */

/* Define the value of SYSTEM-specific OLD-style predefined macro. */
/* #undef SYSTEM_SP_OLD_VAL */

/* Define the name of SYSTEM-specific STD-style predefined macro. */
/* #undef SYSTEM_SP_STD */

/* Define the value of SYSTEM-specific STD-style predefined macro. */
/* #undef SYSTEM_SP_STD_VAL */

/* Version number of package */
#define VERSION "2.4.1"

/* Define like PROTOTYPES; this can be used by system headers. */
#define __PROTOTYPES 1

/* Define to empty if `const' does not conform to ANSI C. */
/* #undef const */

/* Define to `unsigned' if <sys/types.h> does not define. */
/* #undef size_t */
