#!/bin/sh -x
#
KAISUU=5
FIB1=42
FIB2=44
NQ=16
PEN=13
CMP=60000

# ../ntimes $KAISUU c-and-cilk/fib --nproc 1 $FIB1
# ../ntimes $KAISUU c-and-cilk/fib --nproc 2 $FIB1
# ../ntimes $KAISUU c-and-cilk/fib --nproc 4 $FIB1

# ../ntimes $KAISUU c-and-cilk/fib --nproc 1 $FIB2
# ../ntimes $KAISUU c-and-cilk/fib --nproc 2 $FIB2
# ../ntimes $KAISUU c-and-cilk/fib --nproc 4 $FIB2

../ntimes $KAISUU c-and-cilk/nqueen-ac --nproc 1 $NQ
../ntimes $KAISUU c-and-cilk/nqueen-ac --nproc 2 $NQ
../ntimes $KAISUU c-and-cilk/nqueen-ac --nproc 4 $NQ

../ntimes $KAISUU c-and-cilk/nqueen --nproc 1 $NQ
../ntimes $KAISUU c-and-cilk/nqueen --nproc 2 $NQ
../ntimes $KAISUU c-and-cilk/nqueen --nproc 4 $NQ

../ntimes $KAISUU c-and-cilk/nqueen-bt --nproc 1 $NQ
../ntimes $KAISUU c-and-cilk/nqueen-bt --nproc 2 $NQ
../ntimes $KAISUU c-and-cilk/nqueen-bt --nproc 4 $NQ

../ntimes $KAISUU c-and-cilk/pentomino-ac --nproc 1 $PEN
../ntimes $KAISUU c-and-cilk/pentomino-ac --nproc 2 $PEN
../ntimes $KAISUU c-and-cilk/pentomino-ac --nproc 4 $PEN

../ntimes $KAISUU c-and-cilk/pentomino --nproc 1 $PEN
../ntimes $KAISUU c-and-cilk/pentomino --nproc 2 $PEN
../ntimes $KAISUU c-and-cilk/pentomino --nproc 4 $PEN

../ntimes $KAISUU c-and-cilk/pentomino-bt --nproc 1 $PEN
../ntimes $KAISUU c-and-cilk/pentomino-bt --nproc 2 $PEN
../ntimes $KAISUU c-and-cilk/pentomino-bt--nproc 4 $PEN

# ../ntimes $KAISUU c-and-cilk/lu002 --nproc 1 $LU 2
# ../ntimes $KAISUU c-and-cilk/lu002 --nproc 2 $LU 2
# ../ntimes $KAISUU c-and-cilk/lu002 --nproc 4 $LU 2

# ../ntimes $KAISUU c-and-cilk/cmp --nproc 1 $CMP
# ../ntimes $KAISUU c-and-cilk/cmp --nproc 2 $CMP
# ../ntimes $KAISUU c-and-cilk/cmp --nproc 4 $CMP
