#!/bin/sh

usage()
{
    echo "usage: $0 -c <worker_command> -n <n_node> -i <initial_task> -h <hostname> [-p <port_num=9999>] [-l <lisp(alisp|sbcl)>"
    exit 1;
}


# defaults
SERVER_CMDLINE="server-cmdline.lsp"
if [ "x$LISP" = 'x' ]; then
    LISP=alisp
fi
PORT_NUM=8888

# getopts
while getopts l:c:n:i:h:p: opt
do
    case ${opt} in
        l)
            LISP=${OPTARG};;
        c)
            WORKER_CMD=${OPTARG};;
        n)
            NNODE=${OPTARG};;
        i)
            INITIAL_TASK=${OPTARG};;
        h) 
            HOSTNAME=${OPTARG};;
        p)
            PORT_NUM=${OPTARG};;
        *)
            usage $@;;
    esac
done

# check options
if [ "x$WORKER_CMD" = 'x' ]; then
    echo "WORKER_CMD not specified"
    usage $@:;
fi
if [ "x$NNODE" = 'x' ]; then
    echo "NNODE not specified"
    usage $@:;
fi
if [ "x$INITIAL_TASK" = 'x' ]; then
    echo "INITIAL_TASK not specified"
    usage $@:;
fi
if [ "x$HOSTNAME" = 'x' ]; then
    echo "HOSTNAME not specified"
    usage $@:;
fi

set -x

# run
if [ $LISP = 'alisp' ]; then
    "$LISP" -batch -L $SERVER_CMDLINE -- -h $HOSTNAME -p $PORT_NUM -n $NNODE -t "$INITIAL_TASK" &
elif [ $LISP = 'sbcl' ]; then
    "$LISP" --script $SERVER_CMDLINE -h $HOSTNAME -p $PORT_NUM -n $NNODE -t "$INITIAL_TASK" &
else
    echo "Unknown Lisp Implementation: $LISP"
    exit 1
fi
sleep 5

i=1
while [ $i -lt $NNODE ]; do
    set -x
    ./tcpcon $HOSTNAME $PORT_NUM $WORKER_CMD &
    unset -x
    sleep 1
    i=`expr $i + 1`
done
# ./tcpcon $HOSTNAME $PORT_NUM $WORKER_CMD
$WORKER_CMD -s $HOSTNAME -p $PORT_NUM