#! /bin/sh
#XCC="$HOME/../yasugi/tmp/sparc-sol2.6/n3/bin/gcc -DSOL -DCT=lightweight"
XCC="/tmp/local/bin/gcc -DCT=lightweight"
COPTS="-O2 $COPTS"

if [ $# -ge 1 ] && [ `which $1` ]
then
echo "options=$COPTS"
$1 -v
$1 $COPTS qsort-c.c -o sol-qsort-c
$1 $COPTS qsort-gcc.c -o sol-qsort-gcc
$1 $COPTS qsort.c nestfunc.c -o sol-qsort-lw
LANG=C $XCC $COPTS qsort-gcc.c -o sol-qsort-xcc # XC-cube lightweight
$1 $COPTS qsort-clos.c nestfunc.c -o sol-qsort-clos
fi

if [ $# -le 1 ]; then
 m=1
else
 m=$2
fi

n=200000

progs="./sol-qsort-c ./sol-qsort-gcc ./sol-qsort-lw ./sol-qsort-xcc ./sol-qsort-clos"
for prog in $progs; do
    echo $prog
    i=0
    while [ $i -lt $m ]; do
	$prog $n $n
	sleep 1
	i=`expr $i + 1`
    done
done

echo '==='

for prog in $progs; do
    i=0
    while [ $i -le 100 ]; do
	./ntimes 3 ./$prog $n $n $i
	sleep 1
	i=`expr $i + 10`
    done 
    echo ""
done
