#! /bin/sh
#XCC="~yasugi/tmp/i386-linux2.4.20/n1/bin/gcc -DCT=lightweight"
XCC="/tmp/local/bin/gcc -DCT=lightweight"
COPTS="-O2 $COPTS"

if [ $# -ge 1 ] && [ `which $1` ]
then
echo "options=$COPTS"
$1 -v
$1 $COPTS qsort-c.c -o qsort-c
$1 $COPTS qsort-gcc.c -o qsort-gcc
$1 $COPTS qsort.c nestfunc.c -o qsort-lw
LANG=C $XCC -v
LANG=C $XCC $COPTS qsort-gcc.c -o qsort-xcc # XC-cube lightweight
$1 $COPTS qsort-clos.c nestfunc.c -o qsort-clos
fi

if [ $# -le 1 ]; then
 m=1
else
 m=$2
fi

n=200000

progs="./qsort-c ./qsort-gcc ./qsort-lw ./qsort-xcc ./qsort-clos"
for prog in $progs; do
    echo $prog
    i=0
    while [ $i -lt $m ]; do
	$prog $n $n
	sleep 0.3
	i=`expr $i + 1`
    done
done

echo '==='

for prog in $progs; do
    i=0
    while [ $i -le 100 ]; do
	ntimes 3 ./$prog $n $n $i
	sleep 0.3
	i=`expr $i + 10`
    done 
    echo ""
done
