#! /bin/sh
#XCC="$HOME/../yasugi/tmp/sparc-sol2.6/n3/bin/gcc -DSUN -DCT=lightweight"
XCC="/tmp/local/bin/gcc -DCT=lightweight"
COPTS="-O2 $COPTS"

if [ $# -ge 1 ] && [ `which $1` ]
then
echo "options=$COPTS"
$1 -v
$1 $COPTS cpfib0.c -DRAWC -o sol-cpfib-c
$1 $COPTS cpfib0.c -o sol-cpfib-gcc
$1 $COPTS cpfib.c nestfunc.c -o sol-cpfib-lw
LANG=C $XCC -v
LANG=C $XCC $COPTS cpfib0.c copygc0.c -o sol-cpfib-xcc # XC-cube lightweight
$1 $COPTS cpfib-clos.c -o sol-cpfib-clos
fi

if [ $# -le 1 ]; then
 m=1
else
 m=$2
fi

progs="./sol-cpfib-c ./sol-cpfib-gcc ./sol-cpfib-lw ./sol-cpfib-xcc ./sol-cpfib-clos"

arg1=34

for prog in $progs; do
    i=0
    echo $prog
    while [ $i -lt $m ]; do
	$prog $arg1
	i=`expr $i + 1`
    done
    echo ""
done
